ALTER TABLE public.vendors
  ADD COLUMN IF NOT EXISTS w9_file_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS msa_status VARCHAR(50) DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS msa_file_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS acord25_url TEXT NULL,
  ADD COLUMN IF NOT EXISTS coi_status VARCHAR(50) DEFAULT 'PENDING';
